### ISSUE TITLE
Cells blend with the background in jupyter notebooks

### ISSUE THREAD

**Issue by toiletbowlkuku** [ronit18/oXocarbonix-vsc#1]
Great theme btw, love the colors. Unfortunately it doesn't show cells in jupyter notebooks properly.

As you can see:

![Screenshot 2024-12-25 160251](https://github.com/user-attachments/assets/633edbad-b6eb-45ec-bf62-60adb6f5eaf1)

Here's how the cells should look in another theme:

![Screenshot 2024-12-25 160413](https://github.com/user-attachments/assets/7cb9da1a-80a0-4afc-8475-c19279d13582)

**Comment by ronit18** [comment]
Glad to hear you liked it! I have tried to fix it in the latest version, But still there is a visiblity problem because of dark-theme having the darkest black. Still if you find a issue and can fix, please make a pr :)
